# Generated by Django 4.2.8 on 2023-12-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='usuário')),
                ('first_name', models.CharField(max_length=30, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=30, verbose_name='Último Nome')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('user_type', models.CharField(choices=[('manager', 'Síndico'), ('resident', 'Morador')], default='resident', max_length=8, verbose_name='Tipo de Usuário')),
                ('superuser', models.BooleanField(default=False, verbose_name='Admin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
